# Composite service
apiVersion: v1
kind: Service
metadata:
  name: composite-service
  labels:
    app: composite-service
spec:
  selector:
      app: composite-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
