apiVersion: v1
kind: Service
metadata:
  name: spatial-platform-ux
  labels:
    app: spatial-platform-ux
spec:
  selector:
    app: spatial-platform-ux
  ports:
    - port: 3000
      targetPort: 3000
      name: http
