apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: spatial-keycloak
  labels:
    app: spatial
spec:
  instances: {{ .Values.instances }}
  externalDatabase:
    enabled: {{ .Values.externalDatabase.enabled }}
  keycloakDeploymentSpec:
    resources:
      requests:
        cpu: {{ .Values.requestCPU }}
        memory: {{ .Values.requestMemory }}
      limits:
        cpu: {{ .Values.limitCPU }}
        memory: {{ .Values.limitMemory }}
    experimental:
      env:
        - name: KEYCLOAK_LOGLEVEL
          value: INFO
        - name: KEYCLOAK_STATISTICS
          value: all
        - name: KEYCLOAK_WELCOME_THEME
          value: "precisely"
        - name: KEYCLOAK_DEFAULT_THEME
          value: "precisely"
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms64m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar
    - https://github.com/PreciselyData/SpatialAnalytics/releases/download/TP2/keycloak-theme-extension-1.0-SNAPSHOT.jar
  externalAccess:
    enabled: True
    {{- if .Values.global }}
    host: {{ .Values.global.ingress.host | quote}}
    {{- else }}
    host: {{ .Values.ingress.host | quote}}
    {{- end }}
  podDisruptionBudget:
    enabled: True
