apiVersion: v2
name: private-spatial-apis
description: A Helm chart for deploying Private Spatial APIs.

type: application

# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1

appVersion: 1.1.1

dependencies:
  - name: "namedresource-service"
    version: "1.1.1"
    repository: "file://../namedresource-service"
    condition: deployment.namedresource.enabled
  - name: "tiling-service"
    version: "1.1.1"
    repository: "file://../tiling-service"
    condition: deployment.tiling.enabled
  - name: "mapping-service"
    version: "1.1.1"
    repository: "file://../mapping-service"
    condition: deployment.mapping.enabled
  - name: "feature-service"
    version: "1.1.1"
    repository: "file://../feature-service"
    condition: deployment.feature.enabled
  - name: "spatialmanager-service"
    version: "1.1.1"
    repository: "file://../spatialmanager-service"
    condition: deployment.spatialmanager.enabled
  - name: "upload-samples"
    version: "1.1.1"
    repository: "file://../upload-samples"
    condition: deployment.upload-samples.enabled

