# Default values for platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global values
global:
  # Image registry
  registry:
    url: "registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework"
    tag: "latest"
    secrets: "regcred-gitlab"
    
  ingress:
    # A specific host should be specified for ingress when deploying into a namespace other than default.
    #   Host should include full domain name, IP address is not valid.
    #
    host: ""
# Deployment optionals
deployment: 
  feature:
    enabled: true
  mapping:
    enabled: true
  tiling:
    enabled: true
  namedresource:
    enabled: true
  spatialmanager:
    enabled: true
  upload-samples:
    enabled: true
# Service configuration
security:
  enabled: "false"
  oauth2:
    issuerUri: ""
    clientId: ""
    clientSecret: ""
    unsecuredPaths: ""
    requiredAuthority: "user"
    usernameAttribute: "preferred_username"
    userroleAttribute: "role"
url:
  namedresource: "http://namedresource-service:8080"
  feature: "http://feature-service:8080"
  mapping: "http://mapping-service:8080"
  tiling: "http://tiling-service:8080"
repository:
  mongodb:
    url: ""
jvm:
  opts:
    mapping: ""
    feature: ""
    tiling: ""
    namedresource: ""
    spatialmanager: ""
property:
  repositoryCacheCapacity: "1000"
  repositoryCachePolicy: "3"
  repositoryCacheExpire: "1000"
  repositoryFactoryNamedResource: ""
  repositoryFactory: "com.precisely.swp.repository.mongodb.MongoRepositoryFactory"
  repositoryFSRoot: "/opt/data/samples/resources"
  repositoryFSData: ""
  aclManager: "com.precisely.swp.permission.management.keycloak.KeycloakAclPermissionManager"
  timeoutFeatureValue: "-1"
  timeoutMappingValue: "-1"
  poolFileEnabled: "true"
  poolFileMaxTotal: "20"
  poolFileMaxTotalPerKey: "10"
  poolFileMinIdlePerKey: "-1"
  poolFileMaxIdlePerKey: "-1"
  poolFileMaxWaitMillis: "30000"
  poolFileMinEvictableIdleTimeMillis: "60000"
  poolFileNumTestsPerEvictionRun: "1"
  poolFileTestOnBorrow: "false"
  poolFileTestWhileIdle: "false"
  poolFileTimeBetweenEvictionRunsMillis: "10000"
  poolFileBlockWhenExhausted: "false"
  poolDatabaseMaxActive: "10"
  poolDatabaseMaxIdle: "10"
  poolDatabaseMinIdle: "5"
  poolDatabaseInitialSize: "5"
  poolDatabaseTestOnBorrow: "true"
  poolDatabaseJdbcInterceptors: "QueryTimeoutInterceptor(queryTimeout=-1);SlowQueryReport(threshold=1000)"
  poolDatabaseAutoRegisterMBean: "false"
  searchTabCaseInsensitive: "false"
  restrictedPath: "/opt/data"
  subadminConnectionsEnable: "false"
  miRasterCacheSize: "200"
# The END
