###
#   Values for deployment using GitLab container registry
###

# Global
global:
  registry:
    url: ""
    tag: latest
    secrets: regcred
  ingress:
    host: ""
  cors:
    enabled: false
    allowCredentials: false
    allowHeaders: "*"
    allowMethods: "*"
    allowOrigin: "*"
    maxAge: "3600"

# Repository
repository:
  mongodb:
    url: ""
    
# Deployment optionals
deployment: 
  feature:
    enabled: true
  mapping:
    enabled: true
  tiling:
    enabled: true
  resource:
    enabled: true
  data:
    enabled: true
  composite:
    enabled: true
  platform:
    enabled: true
  mcp:
    enabled: true
  upload-samples:
    enabled: false
    
# Security   
security:
  enabled: true
  oauth2:
    issuerUri: ""
    clientId: "spatial"
    clientSecret: ""
  upload:
    clientId: "spatial-data-load"
    clientSecret: ""
    
# JVM options
jvm:
  opts:
    mapping: ""
    feature: ""
    tiling: ""
    resource: ""
    data: ""
    composite: ""
    platform: ""
    mcp: ""

# Properties
property:    
  asyncTransport: "mongo"
  asyncVisibilityTimeout: "5h"
  asyncOperationTTL: "24h"
  asyncMaxRetry: "3"
  asyncConcurrencyWorker: "2"
 
# Individual service overrides
feature-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

mapping-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

tiling-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
resource-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

private-sdk-mcp:
  requestCPU: "100m"
  requestMemory: "512Mi"
  limitCPU: "500m"
  limitMemory: "1Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
composite-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

spatial-platform-ux:
  requestCPU: "100m"
  requestMemory: "500Mi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
data-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

# END

