###
#   Values for deployment using GitLab container registry
###

# Global
global:
  registry:
    url: ""
    tag: latest
    secrets: regcred
  ingress:
    host: 
   
repository:
  mongodb:
    url: "mongodb://mongo-svc.mongo.svc.cluster.local/spatial-repository?authSource=admin&ssl=false"
 
# Individual service overrides
feature-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

mapping-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

tiling-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
resource-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

private-sdk-mcp:
  requestCPU: "100m"
  requestMemory: "512Mi"
  limitCPU: "500m"
  limitMemory: "1Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
composite-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

spatial-platform-ux:
  requestCPU: "100m"
  requestMemory: "500Mi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80
  
data-service:
  requestCPU: "100m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 80

# END

