apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    server: onefsdmx
    path: /dmxk8nfs
  claimRef:
    name: data-volume-claim
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: data-volume-{{ .Release.Namespace }}
