###
#   Values for deployment using JFrog container registry
###

# Global values
global:
  registry:
    url: ""
    tag: latest
    secrets: regcred
  ingress:
    host: ""
  cors:
    enabled: false
    allowCredentials: false
    allowHeaders: "*"
    allowMethods: "*"
    allowOrigin: "*"
    maxAge: "3600"

# Repository
repository:
  mongodb:
    url: ""
    
# Deployment optionals
deployment: 
  feature:
    enabled: true
  mapping:
    enabled: true
  tiling:
    enabled: true
  resource:
    enabled: true
  data:
    enabled: true
  composite:
    enabled: true
  platform:
    enabled: true
  mcp:
    enabled: true
  upload-samples:
    enabled: false
    
# Security   
security:
  enabled: true
  oauth2:
    issuerUri: ""
    clientId: "spatial"
    clientSecret: ""
  upload:
    clientId: "spatial-data-load"
    clientSecret: ""
    
# JVM options
jvm:
  opts:
    mapping: ""
    feature: ""
    tiling: ""
    resource: ""
    data: ""
    composite: ""
    platform: ""
    mcp: ""

# Properties
property:    
  asyncTransport: "jpa"
  asyncVisibilityTimeout: "5h"
  asyncOperationTTL: "24h"
  asyncMaxRetry: "3"
  asyncConcurrencyWorker: "2"

# Individual service overrides
feature-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70

mapping-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70

tiling-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "4"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70

resource-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70
  
data-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70
  
composite-service:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 3
  hpaEnabled: true
  hpaCpuAverageUtilization: 70

spatial-platform-ux:
  requestCPU: "200m"
  requestMemory: "2Gi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 70
  
private-sdk-mcp:
  requestCPU: "200m"
  requestMemory: "100Mi"
  limitCPU: "2"
  limitMemory: "2Gi"
  initReplicaCount: 1
  maxReplicaCount: 2
  hpaEnabled: true
  hpaCpuAverageUtilization: 70

# END

