{{- if .Values.hpaEnabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: namedresource-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: namedresource-service
  minReplicas: {{ .Values.initReplicaCount }}
  maxReplicas: {{ .Values.maxReplicaCount }}
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization : {{ default 80 .Values.hpaCpuAverageUtilization }}
{{- end }}
