apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-service
spec:
  ingressClassName: "nginx"
  rules:
  {{- if .Values.global }}
  - host: {{ .Values.global.ingress.host | quote }}
  {{- else }}
  - host: {{ .Values.ingress.host | quote }}
  {{- end }}
    http:
      paths:
      - path: /rest/Spatial/WFS
        pathType: Prefix
        backend:
          service:
            name: feature-service
            port:
              number: 8080
      - path: /rest/Spatial/FeatureService
        pathType: Prefix
        backend:
          service:
            name: feature-service
            port:
              number: 8080
      - path: /rest/Spatial/DataService
        pathType: Prefix
        backend:
          service:
            name: feature-service
            port:
              number: 8080
      - path: /soap/FeatureService
        pathType: Prefix
        backend:
          service:
            name: feature-service
            port:
              number: 8080
