# Feature service
apiVersion: v1
kind: Service
metadata:
  name: feature-service
  labels:
    app: feature-service
spec:
  selector:
      app: feature-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
