# Mapping/WMS service
apiVersion: v1
kind: Service
metadata:
  name: mapping-service
  labels:
    app: mapping-service
spec:
  selector:
      app: mapping-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
