###
#   Values for deployment using GitLab container registry
###

# Global
global:
  registry:
    url: ""
    tag: latest
    secrets: regcred
  ingress:
    host: 
   
repository:
  mongodb:
    url: "mongodb://mongo-svc.mongo.svc.cluster.local/spatial-repository?authSource=admin&ssl=false"
 
# Individual service overrides
feature-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false

mapping-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  
namedresource-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false

tiling-service:
  requestCPU: "100m"
  limitCPU: null
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false
  
spatialmanager-service:
  requestCPU: "100m"
  limitCPU: "4"
  requestMemory: "2Gi"
  limitMemory: "2Gi"
  initReplicaCount: 1
  hpaEnabled: false

# END

