###
#   Values for deployment using GitLab container registry
###

# Global
global:
  registry:
    url: registry.gitlab.com/preciselydata/location-intelligence/spatial/spatial-web-framework
    tag: latest
    secrets: regcred-gitlab
  ingress:
    host: 

repository:
  mongodb:
    url: "mongodb://mongo-svc.mongo.svc.cluster.local/spatial-repository?authSource=admin&ssl=false"
 
# Individual service overrides
feature-service:
  requestCPU: "4"
  requestMemory: "2G"
  limitCPU: "4"
  limitMemory: "2G"
  initReplicaCount: 1
  maxReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 80

mapping-service:
  requestCPU: "4"
  requestMemory: "2G"
  limitCPU: "4"
  limitMemory: "2G"
  initReplicaCount: 1
  maxReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 80
  
namedresource-service:
  requestCPU: "4"
  requestMemory: "2G"
  limitCPU: "4"
  limitMemory: "2G"
  initReplicaCount: 1
  maxReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 80

tiling-service:
  requestCPU: "4"
  requestMemory: "2G"
  limitCPU: "4"
  limitMemory: "2G"
  initReplicaCount: 1
  maxReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 80

spatialmanager-service:
  requestCPU: "4"
  requestMemory: "2G"
  limitCPU: "4"
  limitMemory: "2G"
  initReplicaCount: 1
  hpaEnabled: false
  hpaCpuAverageUtilization: 80

# END

